name: Test changes

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test calculator.c
        run: |
          gcc calculator.c -lm -o calculator
          echo -e "1\n420\n917" | ./calculator | grep 1337

      - name: Test calculator.py
        run: |
          echo -e "1\n420\n917" | python calculator.py | grep 1337
